name: CI
on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: bash test/checktestdata_tests.sh
